# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('sigla', models.CharField(max_length=200, verbose_name='sigla')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('dataInicio', models.DateTimeField(verbose_name='data de inicio')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('cpf', models.CharField(max_length=15, verbose_name='cpf')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.Pessoa'),
        ),
    ]
